# Version 2.0 ending routes. Gallery flags persist after the title card.

label good_ending:
    scene school_gate_afternoon with fade
    $ player_expression = "happy"
    n "PLAYER bước ra cổng."
    n "Ánh sáng chiều."
    n "Gió."
    n "Không notification."
    n "Không ai gọi tên."
    n "PLAYER dừng lại."
    n "17:03."
    n "Sau gần mười tiếng tồn tại trong môi trường giáo dục…"
    n "PLAYER cuối cùng đã nhìn thấy:"
    n "Cổng trường."
    n "Đường về."
    n "Và quan trọng hơn hết:"
    n "Không còn attendance phía bên kia cánh cổng."
    guard "Về hả em?"
    p "Dạ."
    guard "Hôm nay học dữ ha."
    n "PLAYER nhìn chú."
    p "Chú."
    guard "Hử?"
    p "Chú là người đầu tiên hôm nay nói chuyện với cháu mà không kèm task."
    guard "..."
    n "CHÚ BẢO VỆ bật cười."
    guard "Về nghỉ đi em."
    p "Dạ."
    n "PLAYER bước ra."
    n "Cánh cổng khép lại phía sau."
    n "Không có explosion."
    n "Không có orchestra."
    n "Không có slow motion."
    n "Chỉ có một sinh viên đang đi bộ về nhà."
    n "Nhưng đối với cậu…"
    n "Đó là victory screen."
    scene bedroom_gaming with fade
    centered "HOME — 18:02"
    n "Cửa mở."
    n "Balo rơi xuống ghế."
    p "Home."
    n "PLAYER bật máy."
    n "PC sáng."
    n "Headset lên."
    n "Discord:"
    friend "Game không?"
    n "PLAYER không suy nghĩ dù chỉ một frame."
    p "VÔ."
    friend "Ủa tối nay ông có deadline mà?"
    n "PLAYER đang mở game."
    p "Có."
    friend "Vậy chơi?"
    p "Có sự khác biệt rất lớn."
    friend "Giữa?"
    p "Deadline lúc 23:59."
    p "Và hiện tại mới 18:04."
    friend "Đó là tư duy nguy hiểm."
    p "Đó là tư duy của Future Me."
    n "Notification."
    n "GROUP PROJECT — 12 unread messages"
    n "PLAYER nhìn điện thoại."
    pause 0.3
    n "Úp điện thoại xuống."
    friend "Tin nhắn nhóm à?"
    p "Không thấy."
    friend "Điện thoại vừa sáng mà."
    p "Ảo giác."
    n "Game loading."
    n "PLAYER ngả người ra ghế."
    p "Cuối cùng…"
    n "PLAYER đã sống sót."
    n "Không phải vì cậu hoàn thành tất cả mọi việc."
    n "Không phải vì cậu trở thành sinh viên hoàn hảo."
    n "Mà vì cậu đã học được một kỹ năng cực kỳ quan trọng:"
    centered "Có những việc có thể làm ở nhà."
    n "Và quan trọng hơn:"
    centered "Biết lúc nào nên đi về."
    hide screen stats_hud
    play sound sfx_success
    $ persistent.good_ending_unlocked = True
    $ renpy.save_persistent()
    call screen ending_card("GOOD ENDING", "ESCAPE SUCCESSFUL", "Student Status: ALIVE\nEnergy: Enough for one ranked match\nSanity: Functioning within acceptable parameters\nAssignments: Technically under control\nTomorrow: Future Me's problem\n\nAchievement: LOG OUT SUCCESSFULLY")
    call screen post_ending_actions
    return

label bad_ending:
    scene classroom_afternoon with fade
    centered "17:15"
    p "Ok."
    p "Fix xong."
    l "Nice."
    n "PLAYER bắt đầu đóng laptop."
    l "À."
    n "PLAYER dừng."
    p "Không."
    l "Tui chưa nói gì mà."
    p "Từ ‘à’ đó không bao giờ dẫn tới điều tốt."
    l "Có một cái nhỏ thôi."
    p "Bao nhỏ?"
    l "Responsive UI."
    n "PLAYER ngồi xuống lại."
    $ group_task_done = True
    scene classroom_evening with fade
    centered "18:34"
    p "Done."
    m "Assignment thầy?"
    n "PLAYER dừng gõ."
    p "..."
    m "Ông quên hả?"
    p "Không."
    m "..."
    p "Tôi chỉ tạm thời không nhớ."
    m "Đó là quên."
    p "Đừng dùng logic lúc này."
    scene computer_lab with fade
    centered "20:12"
    n "PLAYER kéo file vào LMS."
    p "Submit."
    n "Loading."
    lms "Upload failed."
    p "Lại."
    n "Upload."
    lms "Invalid file format."
    p "PDF mà."
    lms "Invalid file format."
    p "Cô đang nhìn đúng file không?"
    lms "Accepted formats: PDF."
    n "PLAYER nhìn màn hình."
    p "ĐÂY."
    n "PLAYER chỉ."
    p "LÀ."
    n "PLAYER chỉ mạnh hơn."
    p "PDF."
    lms "Please try again."
    p "..."
    m "Bình tĩnh."
    p "Tôi rất bình tĩnh."
    m "Ông đang nói chuyện với website."
    p "Nó nói chuyện với tôi trước."
    play sound sfx_windows_error
    centered "21:07"
    n "Upload."
    n "Loading."
    lms "Submission saved."
    n "PLAYER đứng dậy."
    p "Xong."
    l "Ê."
    n "PLAYER đứng bất động."
    l "Slide."
    n "PLAYER từ từ quay lại."
    p "Linh."
    l "Hử?"
    p "Nhìn tôi."
    l "Đang nhìn."
    p "Ông thấy một người còn sức làm slide không?"
    l "..."
    m "Còn khoảng 14%%."
    p "Cảm ơn bác sĩ."
    $ assignment_uploaded = True
    $ pending_tasks = max(0, pending_tasks - 1)
    scene classroom_evening with fade
    $ energy = min(energy, 12)
    $ sanity = min(sanity, 4)
    $ player_expression = "exhausted"
    centered "22:18"
    n "Slide mở."
    l "Font nào?"
    p "Poppins."
    m "Montserrat cũng đẹp."
    p "Poppins."
    l "Inter?"
    p "Poppins."
    m "Roboto?"
    p "POPPINS."
    pause 0.3
    l "Ok Poppins."
    p "Cảm ơn."
    p "Tôi không biết tại sao chuyện đó lại khó."
    centered "23:47"
    n "Phòng học gần như tối."
    n "Laptop là nguồn sáng chính."
    n "PLAYER nhấn Save."
    p "Done."
    n "Không ai trả lời."
    n "Minh và Linh đã về từ trước."
    n "PLAYER ngẩng đầu."
    p "..."
    p "Khoan."
    p "Tại sao mình vẫn còn ở đây?"
    n "Đây là câu hỏi PLAYER nên đặt ra khoảng sáu tiếng trước."
    n "PLAYER đứng dậy."
    n "Lưng phát ra tiếng:"
    n "CRACK"
    p "Ah."
    n "Vai:"
    n "CRACK"
    p "..."
    n "Đầu gối:"
    n "CRACK"
    p "Cơ thể?"
    n "PLAYER nhìn tay."
    n "Bàn tay đã khô quéo như vừa trải qua ba semester trong một ngày."
    p "Ồ."
    n "PLAYER nhìn reflection trên màn hình."
    n "Mắt thâm."
    n "Da xám."
    n "Tóc rối."
    n "Linh hồn không còn online."
    p "..."
    p "Understandable."
    n "Sau hơn mười sáu tiếng ở trường…"
    n "Cơ thể PLAYER cuối cùng cũng áp dụng một cơ chế tự bảo vệ."
    n "Nó ngừng cố gắng."
    n "PLAYER đeo balo."
    n "Dáng người giờ trông như một file JPEG bị nén 37 lần."
    p "Về."
    $ energy = 0
    scene school_gate_night with fade
    n "PLAYER lê từng bước ra cổng."
    n "CHÚ BẢO VỆ nhìn thấy."
    guard "Em?"
    p "Dạ…"
    guard "Giờ này mới về?"
    p "Dạ…"
    guard "Học từ sáng à?"
    n "PLAYER mất vài giây để nhớ hôm nay bắt đầu khi nào."
    p "Dạ…"
    n "CHÚ BẢO VỆ nhìn cậu."
    n "PLAYER đứng cong như dấu hỏi."
    n "Hai mắt không còn focus."
    guard "Em ổn không đó?"
    p "Ổn…"
    pause 0.3
    p "Chắc vậy."
    n "Một cơn gió thổi."
    n "PLAYER nghiêng người theo gió."
    guard "Ê ê."
    n "PLAYER lấy lại thăng bằng."
    p "Không sao chú."
    p "Chỉ hơi…"
    n "PLAYER suy nghĩ."
    p "…low battery."
    n "Điện thoại rung."
    centered "LINH"
    n "@everyone sáng mai meeting 7:00 nha"
    n "PLAYER nhìn màn hình."
    n "Một khoảng im lặng rất dài."
    guard "Có chuyện gì vậy em?"
    p "Không có gì chú."
    n "PLAYER khóa điện thoại."
    p "Cháu vừa mất lý do để sống thôi."
    guard "..."
    n "PLAYER lê bước ra cổng."
    hide screen stats_hud
    play sound sfx_bad
    $ persistent.bad_ending_unlocked = True
    $ renpy.save_persistent()
    call screen ending_card("BAD ENDING", "FPT HAS CONSUMED YOU", "Student Status: Technically Alive\nEnergy: 0%%\nSanity: SEGMENTATION FAULT\nPhysical Condition: Dried student\nAssignment: SUBMITTED\nPresentation: UPDATED\nGroup Project: Somehow still has one bug\nTomorrow's Meeting: 07:00\n\nAchievement: JUST ONE MORE TASK")
    scene bedroom_morning with fade
    play sound sfx_alarm
    centered "06:30 AM"
    n "Alarm."
    n "RRRRRRRRRRRR."
    n "Một bàn tay khô héo chui khỏi chăn."
    n "Tắt alarm."
    p "…năm phút."
    n "Màn hình đen."
    n "Text xuất hiện."
    centered "NEW GAME+\nDIFFICULTY UNLOCKED\nSENIOR YEAR"
    n "Good luck."
    call screen post_ending_actions
    return
